### ISSUE TITLE
Implement the IPLD spec

### ISSUE THREAD

**Issue by mildred** [ipfs/go-ipld#20]
This issue is here to track the differences between the current implementation and the IPLD spec:
- [x] ipfs/specs#59 (not yet decided): Convert protobuf messages to the specified format
- [x] ipfs/specs#61 (not yet decided): Encode in CBOR using tags
- [x] ipfs/specs#62 or ipfs/specs#60 (not yet decided): Implement path resolution and walking
- [ ] ipfs/specs#63 and #15: Test that reading a protocol buffer message without the multicodec header works.
- [x] ipfs/specs#64 (not yet decided): Use the correct key for link names (link vs mlink)
- [ ] remove everything about escaping as it seems we don't need it any longer
- [ ] implement changes to spec (as in ipfs/js-ipld#17 and ipfs/specs#101)
- [ ] decide the structure of the code that we were discussing before

If I missed anything, please tell so I can add to the list.

**Comment by jbenet** [comment]
Hey @mildred -- let's get rolling on go-ipld. js-ipld is landing soon. See https://github.com/ipfs/js-ipld/pull/17 and https://github.com/ipfs/specs/issues/97 

I think some of the above checkboxes are done? Yep. checked them.

**Comment by jbenet** [comment]
I think we now need:
- [ ] implement changes to spec (as in https://github.com/ipfs/js-ipld/pull/17 and https://github.com/ipfs/specs/pull/101)
- [ ] decide the structure of the code that we were discussing before

**Comment by mildred** [comment]
> decide the structure of the code that we were discussing before

Could you elaborate? (add a reference)
